### ISSUE TITLE
Error with MinMax-aggregator when only setting `y` (and not `x`)

### ISSUE THREAD

**Issue by jonasvdd** [predict-idlab/tsdownsample#36]
![image](https://user-images.githubusercontent.com/38005924/230404166-3da2553f-0697-4e8c-bacb-897216987fb9.png)

As can be observed from the above screenshot, the minmax aggregator does not properly compute min-max values when the data when the x argument is not passed.

**Comment by jvdd** [comment]
@jonasvdd can you verify whether this is resolved by merging #33

**Comment by jvdd** [comment]
This one seems to be resolved! :tada:
