### ISSUE TITLE
:snake: Python interface not yet stable

### ISSUE THREAD

**Issue by jvdd** [predict-idlab/tsdownsample#5]
:exclamation: :rotating_light: The current Python interface is still under development!!

Some factors that should be taken into account;
- decide whether we go for classes or methods
- flexible datatype support (`pd.Series` seems not ideal, cfr. the bug we uncovered @jonasvdd)
- ...

---

Some other TODOs;
- [x] add `minmax_ratio` to Python bindings of minmaxlttb algorithm (:heavy_check_mark: #4)

(continuation of issue #2 )

**Comment by jvdd** [comment]
Currently the interface is similar to `matplotlib.pyplot.plot` interface:
- `x` and `y` are passed as args (with `x` being optional, i.e., when only 1 arg is passed - we use it as `y`
  => `x` and `y` should be 1D  `np.ndarray`.
- `n_out` should be passed as kwarg
- other kwargs can be placed after `n_out`

---

It might be worthwile to look into polars as dtype for `x` and `y`? :thinking:

**Comment by jonasvdd** [comment]
@jvdd, I think we should then investigate what the "overhead" is of converting `pd.Series` to `polars` representations. (The overhead for `pd.Series` -> `ndarray` is negligable, hence the initial conversion option was more than fair).

**Comment by jonasvdd** [comment]
What also seems a valid `dtype` to support are `xarray` objects.

**Comment by mail4metablocks** [comment]
@jvddI would like to contribute to this project. The performance is really great. Can you give me a lead on which tasks you need research or help in development? I can assist.

**Comment by jvdd** [comment]
Hey @mail4metablocks 

This would be amazing!! :fire:  

To make contributing somewhat easier I just added a [`CONTRIBUTING.md`](https://github.com/predict-idlab/tsdownsample/blob/main/CONTRIBUTING.md) file

You can contribute to the project in various ways:
* A general code review of the Rust code :pray: 
   *(I have written this code by myself, without any code reviews by other people :upside_down_face:, so I am quite sure I might have missed / violated some best practices in Rust.)*
* Profiling & benchmarking 
  => could lead to further improving the performance (it could be possible that I have left something on the table)
  * As stated in the `CONTRIBUTING.md`, this library heavily uses the [argminmax crate](https://github.com/jvdd/argminmax)
    => improving the performance of this package will improve the performance of the `M4`, `MinMax`, and `MinMaxLTTB` downsampler
* Improving the testing (can be for both the Rust & the Python package) - e.g. testing gaps in time series, ... 
* Documentation - documenting the various downsamplers (can be done in the README.md imo)

Cheers, Jeroen

**Comment by jonasvdd** [comment]
I think a worthwhile feature to pursue (for `ArgMinMAx` is creating a `Nan` policy for the float data types):

e.g., add an argument `nan_policy`:
- omit Nans in your comparison (value=`omit`)
- returning the Min and Max as NaN when present  (value='`return`)

**Comment by mail4metablocks** [comment]
Thanks @jonasvdd @jvdd ,I'll begin with the code review and then add some more test cases.

**Comment by jvdd** [comment]
Closing as the interface is matured and already integrated in v0.9 (pre-release) of `plotly-resampler` https://github.com/predict-idlab/plotly-resampler/pull/191
