### ISSUE TITLE
Python 3.12 wheel on pypi

### ISSUE THREAD

**Issue by daveah** [predict-idlab/tsdownsample#71]
Python 3.12 has been out since early October 2023.  Any chance of a cp312 wheel on pypi in the near future?  Whilst we can build locally, tsdownsample does not build easily in our default environment, and this makes using it as a dependency in other libraries problematic.

**Comment by jvdd** [comment]
Should be resolved now as v `0.1.3` is now released: https://pypi.org/project/tsdownsample/
