### ISSUE TITLE
Comparison with Low-Pass Filter?

### ISSUE THREAD

**Issue by lcs-crr** [predict-idlab/tsdownsample#74]
Is there a benchmark comparing the algorithms with "classic" low-pass filter + decimation from control systems?

**Comment by kb-** [comment]
They are 2 different things. Tsdownsample retains the visual aspect of the data. https://arxiv.org/pdf/2206.08703
Low-pass filter + decimation smoothes out any local peak. It removes any feature with frequency content higher than the filter stop frequency.

**Comment by jvdd** [comment]
Will close this as @kb- clearly highlighted the difference between both approaches.
